### ISSUE TITLE
Якщо слово у лапках останнє, то тут ви вийдете за межі довжини рядка, буде виключна ситуація

### ISSUE THREAD

**Issue by KostushkoIA** [MykytaMaliarenko/JavaLabs#3]
https://github.com/MykytaMaliarenko/JavaLabs/blob/b7fa9cb2664337dd5830a19d4f814968573876b9/1/src/com/maliarenko/mykyta/CSVParser.java#L64

Наприклад, такий рядок "12","AU"," ","Australia"

**Comment by MykytaMaliarenko** [comment]
fixed all issues
